
project_id = "hvzqgeeidzkhctoygbts"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://mboa-market-place.lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.lygos-payment]
verify_jwt = false

[functions.lygos-verify]
verify_jwt = false

[functions.lygos-webhook]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329

[analytics]
enabled = false
