// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzqgeeidzkhctoygbts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2enFnZWVpZHpraGN0b3lnYnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjgyMjksImV4cCI6MjA2MjQwNDIyOX0.wUdeHiTxEA2aEeC40Q3ZUOwwpl6h-pNbHwMgXK-gv2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);